<div class="content">
    <?php echo View::content(); ?>
    <h3>Tarjetas</h3>
    
    <TABLE BORDER>
	<TR>
    <TH>Id</TH> 
    <TH>N° Tarjeta</TH> 
    <TH>Saldo Actual</TH> 
    <TH>Saldo Anterior</TH>
    <TH>Saldo Maximo</TH>
    <TH>Saldo Minimo</TH>
	</TR>
    <?php foreach ($listTargetas->items as $item) : ?>
    
	<TR>
		<TD><?php echo $item->id ?></TD> 
        <TD><?php echo $item->_numero_targeta ?></TD> 
        <TD> <?php echo $item->_id_cuenta_asociada?></TD> 
        <TD><?php echo $item->saldo_actual ?></TD>
        <TD> <?php echo $item->saldo_anterior?></TD>
        <TD> <?php echo $item->saldo_maximo?></TD> 
        <TD> <?php echo $item->saldo_minumo?></TD> 
        
        <td><?= Html::linkAction("edit/$item->id/", 'Editar') ?></td>
	</TR>
    <?php endforeach; ?>
    <label><?= Html::linkAction("create/", 'Nueva Tarjeta') ?></label> 
</TABLE>	
    <?php if($listTargetas->prev) echo Html::link("tarjetas/index/$listTargetas->prev/", '<< Anterior |'); ?>
    <?php if($listTargetas->next) echo Html::link("tarjetas/index/$listTargetas->next/", '| Próximo >>'); ?>
</div>