<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP Framework</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php Tag::css('kumbia') ?>
  <?= Html::includeCss() ?>
  <style>
        body{
            
            background: rgb(2,0,36);
            background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(16,233,92,1) 82%, rgba(0,212,255,1) 100%); 
        }
         
    </style>
</head>
<body>
<div class="container">
  <header class="row">
      <div class="col-8">
          <?= Html::link('', Html::img('kumbiaphp.svg', 'KumbiaPHP logo'), 'title="Inicio"') ?>
      </div>
      <div class="col-4 text-right">
          App: <strong><?= basename(dirname(APP_PATH)) ?></strong> (<?= PRODUCTION ? 'Production' : 'Development' ?>)
      </div>
      <style>
        body{
          background: rgb(2,0,36);
          background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(255,252,244,1) 3%, rgba(76,142,226,0.6978991425671831) 91%);  
        }
      </style>
  </header>
  
  <?php View::content() ?>
  <?php View::partial('kumbia/newFooter') ?>
</div>
</body>
</html>
